<?php

/**
 * @file
 * Primary module hooks for node_view_counter module.
 */

use Drupal\Core\Cache\Cache;

/**
 * Implements hook_entity_view().
 */
function node_view_entity_view(array &$build, \Drupal\Core\Entity\EntityInterface $entity, \Drupal\Core\Entity\Display\EntityViewDisplayInterface $display) {
  // Check if the entity is a node.
  if ($entity->getEntityTypeId() === 'node') {
    // Get the current session.
    $session = \Drupal::request()->getSession();
    // Get the node ID.
    $nid = $entity->id();
    $build['#cache'] = [
      '#cache'=>[
        'tags' => ['node:'.$nid,],
      ],
    ];
    // Get the current count from the session.
    $count = $session->get('node_view_count_' . $nid, 0);
    // Increment the count.
    $count++;
    Cache::invalidateTags(['node:' . $nid,]);
    // Store the updated count back in the session.
    $session->set('node_view_count_' . $nid, $count);
    // Add the count to the node render array.
    $messenger = \Drupal::messenger();
    $messenger->addStatus(t('This node has been viewed @count times in this session.', ['@count' => $count]));
  }
}
